# Bias vs Variance  overfit test err = 100 underfit test err = 27 balanced fit  high variance
Test error varies greatly based on the selection of the training dataset
Linear Regressionn is underfit training err is 43 & test err is 47 low variance
Bias is a measurement of how accurately a model can capture a pattern in a training dataset.In above case since train err is big it is said to have a high bias
variance -> test err
bias --> test err
both low idle conditions low variance,low bias model
Balanced fit --> cross validation(KFOLD),Regularization(L1 & L2),Dimensionality Reduction(PCA),Ensemble Techniques(Bagging & Boosting)

 # Bagging & Boosting

resampling with replacement like 10 in (4,8,4,9)like subsets
3 sets like m1,m2,m3 if a person would buy insurance or not m1 gives 1,0,1 majority is 1
# Bootstrap & Aggregation-->bagging
Random Forest algorithm is a one of bagging technique
7 cols --> 4 diff cols->then 3 diff cols-->4 diff cols-->avg score
Bagging -->Underlying model can be anything(svm,knn,logistic regression etc..)
Bagged trees --> Each model is a tree

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\ML_CSV\\diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
df.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [7]:
268/500

0.536

In [9]:
X = df.drop("Outcome",axis='columns')
y = df.Outcome

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled[:3]

array([[ 0.63994726,  0.84832379,  0.14964075,  0.90726993, -0.69289057,
         0.20401277,  0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575,  0.53090156, -0.69289057,
        -0.68442195, -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, -1.28821221, -0.69289057,
        -1.10325546,  0.60439732, -0.10558415]])

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_scaled,y,stratify=y,random_state=10)

In [12]:
X_train.shape

(576, 8)

In [14]:
y_train.value_counts()

Outcome
0    375
1    201
Name: count, dtype: int64

In [15]:
201/375

0.536

In [16]:
from sklearn.tree import DecisionTreeClassifier # it is a overfit classifer gives high variance
from sklearn.model_selection import cross_val_score
scores = cross_val_score(DecisionTreeClassifier(),X,y,cv=5)
scores

array([0.74025974, 0.66233766, 0.68831169, 0.75816993, 0.71895425])

In [17]:
scores.mean()

np.float64(0.7136066547831253)

In [20]:
from sklearn.ensemble import BaggingClassifier
#oob out of bag
bagmodel = BaggingClassifier(
        estimator = DecisionTreeClassifier(),
        n_estimators = 100,
        max_samples = 0.8,
        oob_score = True,
        random_state = 0
)
bagmodel.fit(X_train,y_train)
bagmodel.oob_score_

0.7534722222222222

In [21]:
bagmodel.fit(X_test,y_test)

BaggingClassifier(estimator=DecisionTreeClassifier(), max_samples=0.8,
                  n_estimators=100, oob_score=True, random_state=0)

In [22]:
bagmodel.oob_score_

0.7604166666666666

In [25]:
bagmodel = BaggingClassifier(
        estimator = DecisionTreeClassifier(),
        n_estimators = 100,
        max_samples = 0.8,
        oob_score = True,
        random_state = 0
)
scores = cross_val_score(bagmodel,X,y,cv=5)
scores.mean() #Bagged model has high accuracy

np.float64(0.7578728461081402)

In [27]:
from sklearn.ensemble import RandomForestClassifier
scores = cross_val_score(RandomForestClassifier(),X,y,cv=5)
scores.mean()# underlying it is used bagging

np.float64(0.7592055003819709)

# Example

In [28]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\ML_CSV\\heart.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [29]:
df.shape

(918, 12)

In [30]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [31]:
df[df.Cholesterol>(df.Cholesterol.mean()+3*df.Cholesterol.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
76,32,M,ASY,118,529,0,Normal,130,N,0.0,Flat,1
149,54,M,ASY,130,603,1,Normal,125,Y,1.0,Flat,1
616,67,F,NAP,115,564,0,LVH,160,N,1.6,Flat,0

In [32]:
df1 = df[df.Cholesterol<=(df.Cholesterol.mean()+3*df.Cholesterol.std())]
df1.shape

(915, 12)

In [33]:
df[df.MaxHR>(df.MaxHR.mean()+3*df.MaxHR.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [34]:

df[df.FastingBS>(df.FastingBS.mean()+3*df.FastingBS.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [35]:
df[df.Oldpeak>(df.Oldpeak.mean()+3*df.Oldpeak.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
166,50,M,ASY,140,231,0,ST,140,Y,5.0,Flat,1
702,59,M,TA,178,270,0,LVH,145,N,4.2,Down,0
771,55,M,ASY,140,217,0,Normal,111,Y,5.6,Down,1
791,51,M,ASY,140,298,0,Normal,122,Y,4.2,Flat,1
850,62,F,ASY,160,164,0,LVH,145,N,6.2,Down,1
900,58,M,ASY,114,318,0,ST,140,N,4.4,Down,1

In [36]:
df2 = df1[df1.Oldpeak<=(df1.Oldpeak.mean()+3*df1.Oldpeak.std())]
df2.shape

(909, 12)

In [37]:
df[df.RestingBP>(df.RestingBP.mean()+3*df.RestingBP.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
109,39,M,ATA,190,241,0,Normal,106,N,0.0,Up,0
241,54,M,ASY,200,198,0,Normal,142,Y,2.0,Flat,1
365,64,F,ASY,200,0,0,Normal,140,Y,1.0,Flat,1
399,61,M,NAP,200,0,1,ST,70,N,0.0,Flat,1
592,61,M,ASY,190,287,1,LVH,150,Y,2.0,Down,1
732,56,F,ASY,200,288,1,LVH,133,Y,4.0,Down,1
759,54,M,ATA,192,283,0,LVH,195,N,0.0,Up,1

In [38]:
df3 = df2[df2.RestingBP<=(df2.RestingBP.mean()+3*df2.RestingBP.std())]
df3.shape

(902, 12)

In [39]:
df.ChestPainType.unique()

<StringArray>
['ATA', 'NAP', 'ASY', 'TA']
Length: 4, dtype: str

In [40]:
df.RestingECG.unique()

<StringArray>
['Normal', 'ST', 'LVH']
Length: 3, dtype: str

In [41]:
df.ExerciseAngina.unique()

<StringArray>
['N', 'Y']
Length: 2, dtype: str

In [42]:
df.ST_Slope.unique()

<StringArray>
['Up', 'Flat', 'Down']
Length: 3, dtype: str

In [45]:
df4 = df3.copy()
# ✅ Correct way
df4.replace({'ExerciseAngina': {'Y': 1, 'N': 0}}, inplace=True)
df4.replace({'ST_Slope': {'Up': 2, 'Flat': 1, 'Down': 0}}, inplace=True)
df4.replace({'RestingECG': {'Normal': 0, 'ST': 1, 'LVH': 2}}, inplace=True)
df4.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,0,172,0,0.0,2,0
1,49,F,NAP,160,180,0,0,156,0,1.0,1,1
2,37,M,ATA,130,283,0,1,98,0,0.0,2,0
3,48,F,ASY,138,214,0,0,108,1,1.5,1,1
4,54,M,NAP,150,195,0,0,122,0,0.0,2,0

In [46]:
df5 = pd.get_dummies(df4, drop_first=True)
df5.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_1,RestingECG_2,ExerciseAngina_1,ST_Slope_1,ST_Slope_2
0,40,140,289,0,172,0.0,0,True,True,False,False,False,False,False,False,True
1,49,160,180,0,156,1.0,1,False,False,True,False,False,False,False,True,False
2,37,130,283,0,98,0.0,0,True,True,False,False,True,False,False,False,True
3,48,138,214,0,108,1.5,1,False,False,False,False,False,False,True,True,False
4,54,150,195,0,122,0.0,0,True,False,True,False,False,False,False,False,True

In [47]:
X = df5.drop("HeartDisease",axis='columns')
y = df5.HeartDisease

X.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_1,RestingECG_2,ExerciseAngina_1,ST_Slope_1,ST_Slope_2
0,40,140,289,0,172,0.0,True,True,False,False,False,False,False,False,True
1,49,160,180,0,156,1.0,False,False,True,False,False,False,False,True,False
2,37,130,283,0,98,0.0,True,True,False,False,True,False,False,False,True
3,48,138,214,0,108,1.5,False,False,False,False,False,False,True,True,False
4,54,150,195,0,122,0.0,True,False,True,False,False,False,False,False,True

In [48]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-1.42896269,  0.46089071,  0.85238015, ..., -0.82065181,
        -1.00221976,  1.13805334],
       [-0.47545956,  1.5925728 , -0.16132855, ..., -0.82065181,
         0.99778516, -0.87869344],
       [-1.74679706, -0.10495034,  0.79657967, ..., -0.82065181,
        -1.00221976,  1.13805334],
       ...,
       [ 0.37209878, -0.10495034, -0.61703246, ...,  1.21854359,
         0.99778516, -0.87869344],
       [ 0.37209878, -0.10495034,  0.35947592, ..., -0.82065181,
         0.99778516, -0.87869344],
       [-1.64085227,  0.3477225 , -0.20782894, ..., -0.82065181,
        -1.00221976,  1.13805334]])

In [49]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=20)

In [50]:
X_train.shape

(721, 15)

In [52]:
X_test.shape

(181, 15)

Train a model using standalone support vector machine and then using bagging

In [53]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score

scores = cross_val_score(SVC(), X, y, cv=5)
scores.mean()

np.float64(0.6895273173726213)

In [54]:
from sklearn.ensemble import BaggingClassifier

bag_model = BaggingClassifier(estimator=SVC(), n_estimators=100, max_samples=0.8, random_state=0)
scores = cross_val_score(bag_model, X, y, cv=5)
scores.mean()

np.float64(0.6850767341927564)

As you can see above, using bagging in case of SVM doesn't make much difference in terms of model accuracy. Bagging is effective when we have high variance and instable model such as decision tree. Let's explore how bagging changes the performance for a decision tree classifier.

Train a model using decision tree and then using bagging

In [55]:
from sklearn.tree import DecisionTreeClassifier

scores = cross_val_score(DecisionTreeClassifier(random_state=0), X, y, cv=5)
scores.mean()

np.float64(0.7304910988336404)

In [56]:
bag_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(random_state=0), 
    n_estimators=100, 
    max_samples=0.9, 
    oob_score=True,
    random_state=0
)

scores = cross_val_score(bag_model, X, y, cv=5)
scores.mean()

np.float64(0.8025905463474524)

You can see that with bagging the score improved from 71.93% to 80.37%

Train a model using Random Forest which itself uses bagging underneath

In [57]:
from sklearn.ensemble import RandomForestClassifier

scores = cross_val_score(RandomForestClassifier(), X, y, cv=5)
scores.mean()

np.float64(0.8203314917127071)

Random forest gave even a better performance with 81.7% as score. Underneath it used bagging where it sampled not only data rows but also the columns (or features)